### ISSUE TITLE
Cannot run the code

### ISSUE THREAD

**Issue by MatthewCYM** [ucbrise/graphtrans#4]
Hi,

I try to run your code through
```
config=configs/molpcba/gnn-transformer/no-virtual/JK=cat/pooling=cls+gin+norm_input.yml


echo "python main.py --configs $config --num_workers 8 --devices $CUDA_VISIBLE_DEVICES"

/home/yiming/anaconda3/envs/graphtrans/bin/python main.py \
              --configs $config \
              --num_workers 8 \
              --data_root data/ogb \
              --devices $CUDA_VISIBLE_DEVICES
```

However, it shows the below error:
```
Traceback (most recent call last):
  File "main.py", line 280, in <module>
    main()
  File "main.py", line 155, in main
    train_loader_, train_loader_eval_, valid_loader_, test_loader_ = create_loader(dataset_, dataset_eval_)
  File "main.py", line 143, in create_loader
    test_data = compute_adjacency_list_cached(dataset[split_idx["test"]], key=f"{args.dataset}_test")
  File "/home/yiming/graphtrans/data/adj_list.py", line 45, in compute_adjacency_list_cached
    result = compute_adjacency_list(data)
  File "/home/yiming/graphtrans/data/adj_list.py", line 26, in compute_adjacency_list
    out.append(make_adj_list_wrapper(x))
  File "/home/yiming/graphtrans/data/adj_list.py", line 20, in make_adj_list_wrapper
    return make_adj_list(x["num_nodes"], x["edge_index"].T)
  File "/home/yiming/anaconda3/envs/graphtrans/lib/python3.8/site-packages/torch_geometric/data/data.py", line 371, in __getitem__
    return self._store[key]
  File "/home/yiming/anaconda3/envs/graphtrans/lib/python3.8/site-packages/torch_geometric/data/storage.py", line 70, in __getitem__
    return self._mapping[key]
KeyError: 'num_nodes'
```

May I ask how to fix this?

Thank you!

Yiming

**Comment by Michaelvll** [comment]
Thank you for trying it out! What is the version of PyG you are using? It is possible that PyG is not backward compatible.

**Comment by MatthewCYM** [comment]
Hi,

I am using 2.0.4. I fix the bug by modifying
```
return make_adj_list(x["num_nodes"], x["edge_index"].T)
```
to
```
return make_adj_list(x.num_nodes, x["edge_index"].T)
```
May I ask if this is the correct way?

Thank you!

**Comment by Michaelvll** [comment]
Yes, I think that would be a correct fix. Thank you for the solution!
